name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    permissions: write-all
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number}}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

  release_assets_ubuntu:
    name: Release assets ub
    needs: create_release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Upload release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url}}
          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.zip
          asset_path: ./helloworld-0.0.${{ github.run_number }}-Linux.zip
          asset_content_type: application/vnd.debian.binary-package

  release_assets_windows:
    name: Build Windows
    needs: create_release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Boost
        run: |
          vcpkg integrate install
          vcpkg install boost-test
      
      - name: Configure CMake
        run: cmake -B build -DPATCH_VERSION=${{ github.run_number }} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
      
      - name: Build
        run: cmake --build build --config Release
      
      - name: Run tests
        run: ctest --test-dir build --build-config Release
      
      - name: Create package
        run: cmake --build build --target package --config Release
      
      - name: Upload asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build/*.zip
          asset_content_type: application/zip
          with:
            upload_url: ${{ needs.create_release.outputs.upload_url}}
            asset_name: helloworld-0.0.${{ github.run_number }}-Windows.zip
            asset_path: ./build/helloworld-0.0.${{ github.run_number }}-win64.zip
            asset_content_type: application/zip
